platform:
- x64
- x86

environment:
  matrix:

  - BUILD_TYPE: nmake

# Does not work
# VS 2008
#  - BUILD_TYPE: cmake
#    VS_VERSION: Visual Studio 9 2008

# VS 2010
  - BUILD_TYPE: nmake
    VS_VERSION: Visual Studio 10

# VS 2015
  - BUILD_TYPE: nmake
    VS_VERSION: Visual Studio 14

shallow_clone: true

build_script:
  - echo build_script
  - if "%BUILD_TYPE%" == "nmake" if "%platform%" == "x86" call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat"
  - if "%BUILD_TYPE%" == "nmake" if "%platform%" == "x64" "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - if "%BUILD_TYPE%" == "nmake" if "%platform%" == "x64" call "%VS120COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - if "%BUILD_TYPE%" == "nmake" nmake /f makefile.vc
  - if "%BUILD_TYPE%" == "nmake" nmake /f makefile.vc install-all
  - if "%BUILD_TYPE%" == "nmake" if "%platform%" == "x64" cd src
  - if "%BUILD_TYPE%" == "nmake" if "%platform%" == "x64" nmake /f makefile.vc multistresstest.exe
# Disabled for now as it scales badly
#  - if "%BUILD_TYPE%" == "nmake" if "%platform%" == "x64" multistresstest.exe

test_script:
  - echo test_script

deploy: off
